/**
 * Any copyright is dedicated to the Public Domain.
 * http://creativecommons.org/publicdomain/zero/1.0/
 *
 * From MDN:
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Examples/Deriving_the_Quadratic_Formula
 */

import * as DeStagnate from "../../../"

document.getElementById("mathML")?.appendChild(
    <div class="bg-tertiary p-3 d-flex justify-content-center">
        <mathML:math>
            <mathML:mtable>
                <mathML:mtr>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mrow>
                                <mathML:mrow>
                                    <mathML:mrow>
                                        <mathML:mi>a</mathML:mi>
                                        <mathML:mo>&#x2062;{/* INVISIBLE TIMES */}</mathML:mo>
                                        <mathML:msup>
                                            <mathML:mi>x</mathML:mi>
                                            <mathML:mn>2</mathML:mn>
                                        </mathML:msup>
                                    </mathML:mrow>
                                    <mathML:mo>+</mathML:mo>
                                    <mathML:mi>b</mathML:mi>
                                    <mathML:mo>&#x2062;{/* INVISIBLE TIMES */}</mathML:mo>
                                    <mathML:mi>x</mathML:mi>
                                </mathML:mrow>
                                <mathML:mo>+</mathML:mo>
                                <mathML:mi>c</mathML:mi>
                            </mathML:mrow>
                        </mathML:mrow>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mo>=</mathML:mo>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mn>0</mathML:mn>
                    </mathML:mtd>
                </mathML:mtr>
                <mathML:mtr>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mrow>
                                <mathML:mi>a</mathML:mi>
                                <mathML:mo>&#x2062;{/* INVISIBLE TIMES */}</mathML:mo>
                                <mathML:msup>
                                    <mathML:mi>x</mathML:mi>
                                    <mathML:mn>2</mathML:mn>
                                </mathML:msup>
                            </mathML:mrow>
                            <mathML:mo>+</mathML:mo>
                            <mathML:mi>b</mathML:mi>
                            <mathML:mo>&#x2062;{/* INVISIBLE TIMES */}</mathML:mo>
                            <mathML:mi>x</mathML:mi>
                        </mathML:mrow>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mo>=</mathML:mo>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mo>−</mathML:mo>
                        <mathML:mi>c</mathML:mi>
                    </mathML:mtd>
                </mathML:mtr>
                <mathML:mtr>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mrow>
                                <mathML:msup>
                                    <mathML:mi>x</mathML:mi>
                                    <mathML:mn>2</mathML:mn>
                                </mathML:msup>
                            </mathML:mrow>
                            <mathML:mo>+</mathML:mo>
                            <mathML:mfrac>
                                <mathML:mi>b</mathML:mi>
                                <mathML:mi>a</mathML:mi>
                            </mathML:mfrac>
                            <mathML:mo>⁤</mathML:mo>
                            <mathML:mi>x</mathML:mi>
                        </mathML:mrow>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mo>=</mathML:mo>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mfrac>
                            <mathML:mrow>
                                <mathML:mo>−</mathML:mo>
                                <mathML:mi>c</mathML:mi>
                            </mathML:mrow>
                            <mathML:mi>a</mathML:mi>
                        </mathML:mfrac>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mtext style="color: red; font-size: 10pt;">
                                Divide out leading coefficient.
                            </mathML:mtext>
                        </mathML:mrow>
                    </mathML:mtd>
                </mathML:mtr>
                <mathML:mtr>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mrow>
                                <mathML:mrow>
                                    <mathML:msup>
                                        <mathML:mi>x</mathML:mi>
                                        <mathML:mn>2</mathML:mn>
                                    </mathML:msup>
                                </mathML:mrow>
                                <mathML:mo>+</mathML:mo>
                                <mathML:mfrac>
                                    <mathML:mrow>
                                        <mathML:mi>b</mathML:mi>
                                    </mathML:mrow>
                                    <mathML:mi>a</mathML:mi>
                                </mathML:mfrac>
                                <mathML:mo>⁤</mathML:mo>
                                <mathML:mi>x</mathML:mi>
                                <mathML:mo>+</mathML:mo>
                                <mathML:msup>
                                    <mathML:mrow>
                                        <mathML:mo>(</mathML:mo>
                                        <mathML:mfrac>
                                            <mathML:mrow>
                                                <mathML:mi>b</mathML:mi>
                                            </mathML:mrow>
                                            <mathML:mrow>
                                                <mathML:mn>2</mathML:mn>
                                                <mathML:mi>a</mathML:mi>
                                            </mathML:mrow>
                                        </mathML:mfrac>
                                        <mathML:mo>)</mathML:mo>
                                    </mathML:mrow>
                                    <mathML:mn>2</mathML:mn>
                                </mathML:msup>
                            </mathML:mrow>
                        </mathML:mrow>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mo>=</mathML:mo>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mfrac>
                                <mathML:mrow>
                                    <mathML:mo>−</mathML:mo>
                                    <mathML:mi>c</mathML:mi>
                                    <mathML:mo>(</mathML:mo>
                                    <mathML:mn>4</mathML:mn>
                                    <mathML:mi>a</mathML:mi>
                                    <mathML:mo>)</mathML:mo>
                                </mathML:mrow>
                                <mathML:mrow>
                                    <mathML:mi>a</mathML:mi>
                                    <mathML:mo>(</mathML:mo>
                                    <mathML:mn>4</mathML:mn>
                                    <mathML:mi>a</mathML:mi>
                                    <mathML:mo>)</mathML:mo>
                                </mathML:mrow>
                            </mathML:mfrac>
                            <mathML:mo>+</mathML:mo>
                            <mathML:mfrac>
                                <mathML:mrow>
                                    <mathML:msup>
                                        <mathML:mi>b</mathML:mi>
                                        <mathML:mn>2</mathML:mn>
                                    </mathML:msup>
                                </mathML:mrow>
                                <mathML:mrow>
                                    <mathML:mn>4</mathML:mn>
                                    <mathML:msup>
                                        <mathML:mi>a</mathML:mi>
                                        <mathML:mn>2</mathML:mn>
                                    </mathML:msup>
                                </mathML:mrow>
                            </mathML:mfrac>
                        </mathML:mrow>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mtext style="color: red; font-size: 10pt;">
                                Complete the square.
                            </mathML:mtext>
                        </mathML:mrow>
                    </mathML:mtd>
                </mathML:mtr>
                <mathML:mtr>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mrow>
                                <mathML:mo>(</mathML:mo>
                                <mathML:mi>x</mathML:mi>
                                <mathML:mo>+</mathML:mo>
                                <mathML:mfrac>
                                    <mathML:mrow>
                                        <mathML:mi>b</mathML:mi>
                                    </mathML:mrow>
                                    <mathML:mrow>
                                        <mathML:mn>2</mathML:mn>
                                        <mathML:mi>a</mathML:mi>
                                    </mathML:mrow>
                                </mathML:mfrac>
                                <mathML:mo>)</mathML:mo>
                                <mathML:mo>(</mathML:mo>
                                <mathML:mi>x</mathML:mi>
                                <mathML:mo>+</mathML:mo>
                                <mathML:mfrac>
                                    <mathML:mrow>
                                        <mathML:mi>b</mathML:mi>
                                    </mathML:mrow>
                                    <mathML:mrow>
                                        <mathML:mn>2</mathML:mn>
                                        <mathML:mi>a</mathML:mi>
                                    </mathML:mrow>
                                </mathML:mfrac>
                                <mathML:mo>)</mathML:mo>
                            </mathML:mrow>
                        </mathML:mrow>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mo>=</mathML:mo>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mfrac>
                            <mathML:mrow>
                                <mathML:msup>
                                    <mathML:mi>b</mathML:mi>
                                    <mathML:mn>2</mathML:mn>
                                </mathML:msup>
                                <mathML:mo>−</mathML:mo>
                                <mathML:mn>4</mathML:mn>
                                <mathML:mi>a</mathML:mi>
                                <mathML:mi>c</mathML:mi>
                            </mathML:mrow>
                            <mathML:mrow>
                                <mathML:mn>4</mathML:mn>
                                <mathML:msup>
                                    <mathML:mi>a</mathML:mi>
                                    <mathML:mn>2</mathML:mn>
                                </mathML:msup>
                            </mathML:mrow>
                        </mathML:mfrac>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mtext style="color: red; font-size: 10pt;">
                                Discriminant revealed.
                            </mathML:mtext>
                        </mathML:mrow>
                    </mathML:mtd>
                </mathML:mtr>
                <mathML:mtr>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mrow>
                                <mathML:msup>
                                    <mathML:mrow>
                                        <mathML:mo>(</mathML:mo>
                                        <mathML:mi>x</mathML:mi>
                                        <mathML:mo>+</mathML:mo>
                                        <mathML:mfrac>
                                            <mathML:mrow>
                                                <mathML:mi>b</mathML:mi>
                                            </mathML:mrow>
                                            <mathML:mrow>
                                                <mathML:mn>2</mathML:mn>
                                                <mathML:mi>a</mathML:mi>
                                            </mathML:mrow>
                                        </mathML:mfrac>
                                        <mathML:mo>)</mathML:mo>
                                    </mathML:mrow>
                                    <mathML:mn>2</mathML:mn>
                                </mathML:msup>
                            </mathML:mrow>
                        </mathML:mrow>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mo>=</mathML:mo>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mfrac>
                            <mathML:mrow>
                                <mathML:msup>
                                    <mathML:mi>b</mathML:mi>
                                    <mathML:mn>2</mathML:mn>
                                </mathML:msup>
                                <mathML:mo>−</mathML:mo>
                                <mathML:mn>4</mathML:mn>
                                <mathML:mi>a</mathML:mi>
                                <mathML:mi>c</mathML:mi>
                            </mathML:mrow>
                            <mathML:mrow>
                                <mathML:mn>4</mathML:mn>
                                <mathML:msup>
                                    <mathML:mi>a</mathML:mi>
                                    <mathML:mn>2</mathML:mn>
                                </mathML:msup>
                            </mathML:mrow>
                        </mathML:mfrac>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mtext style="color: red; font-size: 10pt;"></mathML:mtext>
                        </mathML:mrow>
                    </mathML:mtd>
                </mathML:mtr>
                <mathML:mtr>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mrow>
                                <mathML:mrow>
                                    <mathML:mi>x</mathML:mi>
                                    <mathML:mo>+</mathML:mo>
                                    <mathML:mfrac>
                                        <mathML:mrow>
                                            <mathML:mi>b</mathML:mi>
                                        </mathML:mrow>
                                        <mathML:mrow>
                                            <mathML:mn>2</mathML:mn>
                                            <mathML:mi>a</mathML:mi>
                                        </mathML:mrow>
                                    </mathML:mfrac>
                                </mathML:mrow>
                            </mathML:mrow>
                        </mathML:mrow>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mo>=</mathML:mo>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:msqrt>
                            <mathML:mfrac>
                                <mathML:mrow>
                                    <mathML:msup>
                                        <mathML:mi>b</mathML:mi>
                                        <mathML:mn>2</mathML:mn>
                                    </mathML:msup>
                                    <mathML:mo>−</mathML:mo>
                                    <mathML:mn>4</mathML:mn>
                                    <mathML:mi>a</mathML:mi>
                                    <mathML:mi>c</mathML:mi>
                                </mathML:mrow>
                                <mathML:mrow>
                                    <mathML:mn>4</mathML:mn>
                                    <mathML:msup>
                                        <mathML:mi>a</mathML:mi>
                                        <mathML:mn>2</mathML:mn>
                                    </mathML:msup>
                                </mathML:mrow>
                            </mathML:mfrac>
                        </mathML:msqrt>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mtext style="color: red; font-size: 10pt;"></mathML:mtext>
                        </mathML:mrow>
                    </mathML:mtd>
                </mathML:mtr>
                <mathML:mtr>
                    <mathML:mtd>
                        <mathML:mi>x</mathML:mi>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mo>=</mathML:mo>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mfrac>
                            <mathML:mrow>
                                <mathML:mo>−</mathML:mo>
                                <mathML:mi>b</mathML:mi>
                            </mathML:mrow>
                            <mathML:mrow>
                                <mathML:mn>2</mathML:mn>
                                <mathML:mi>a</mathML:mi>
                            </mathML:mrow>
                        </mathML:mfrac>
                        <mathML:mo>±</mathML:mo>
                        <mathML:mrow>
                            <mathML:mo>{"{"}</mathML:mo>
                            <mathML:mi>C</mathML:mi>
                            <mathML:mo>{"}"}</mathML:mo>
                        </mathML:mrow>
                        <mathML:msqrt>
                            <mathML:mfrac>
                                <mathML:mrow>
                                    <mathML:msup>
                                        <mathML:mi>b</mathML:mi>
                                        <mathML:mn>2</mathML:mn>
                                    </mathML:msup>
                                    <mathML:mo>−</mathML:mo>
                                    <mathML:mn>4</mathML:mn>
                                    <mathML:mi>a</mathML:mi>
                                    <mathML:mi>c</mathML:mi>
                                </mathML:mrow>
                                <mathML:mrow>
                                    <mathML:mn>4</mathML:mn>
                                    <mathML:msup>
                                        <mathML:mi>a</mathML:mi>
                                        <mathML:mn>2</mathML:mn>
                                    </mathML:msup>
                                </mathML:mrow>
                            </mathML:mfrac>
                        </mathML:msqrt>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mtext style="color: red; font-size: 10pt;">
                                There's the vertex formula.
                            </mathML:mtext>
                        </mathML:mrow>
                    </mathML:mtd>
                </mathML:mtr>
                <mathML:mtr>
                    <mathML:mtd>
                        <mathML:mi>x</mathML:mi>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mo>=</mathML:mo>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mfrac>
                            <mathML:mrow>
                                <mathML:mo>−</mathML:mo>
                                <mathML:mi>b</mathML:mi>
                                <mathML:mo>±</mathML:mo>
                                <mathML:mrow>
                                    <mathML:mo>{"{"}</mathML:mo>
                                    <mathML:mi>C</mathML:mi>
                                    <mathML:mo>{"}"}</mathML:mo>
                                </mathML:mrow>
                                <mathML:msqrt>
                                    <mathML:msup>
                                        <mathML:mi>b</mathML:mi>
                                        <mathML:mn>2</mathML:mn>
                                    </mathML:msup>
                                    <mathML:mo>−</mathML:mo>
                                    <mathML:mn>4</mathML:mn>
                                    <mathML:mi>a</mathML:mi>
                                    <mathML:mi>c</mathML:mi>
                                </mathML:msqrt>
                            </mathML:mrow>
                            <mathML:mrow>
                                <mathML:mn>2</mathML:mn>
                                <mathML:mi>a</mathML:mi>
                            </mathML:mrow>
                        </mathML:mfrac>
                    </mathML:mtd>
                    <mathML:mtd>
                        <mathML:mrow>
                            <mathML:mtext style="color: red; font-size: 10pt;"></mathML:mtext>
                        </mathML:mrow>
                    </mathML:mtd>
                </mathML:mtr>
            </mathML:mtable>
        </mathML:math>
    </div>,
)
