# Normal Options
arrowParens: "always"
bracketSpacing: false
embeddedLanguageFormatting: "auto"
endOfLine: "lf"
htmlWhitespaceSensitivity: "css"
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 99
quoteProps: "as-needed"
semi: false
singleQuote: false
tabWidth: 4
trailingComma: "all"
useTabs: false

plugins:
  - prettier-plugin-jsdoc
  - prettier-plugin-package

overrides:
  - files:
      - "*.html"
      - "*.yml"
      - "*.yaml"
      - "*.json"
      - "*.css"
      - "*.scss"
    options:
      tabWidth: 2
  - files:
      - "stateContainer.ts"
    options:
      plugins: [] # Disable jsdoc formatter

  - files:
      - "jsx.ts"
    options:
      printWidth: 200
