name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: install deps
        run: yarn install --frozen-lockfile

      - name: lint
        run: make lint

      - name: build
        run: bash build.sh --no-docs

      - name: upload lib
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: lib

      - name: upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  test:
    name: test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: install deps
        run: yarn --frozen-lockfile

      - name: test
        run: yarn test

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: install deps
        run: yarn --frozen-lockfile

      - name: test coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: 0bedacb0cc32f53df1879d3fcd8ffc561c73e241ebefaaf7e6b464549fef6b29
        with:
          coverageCommand:  yarn coverage
          coverageLocations: ${{github.workspace}}/coverage/clover.xml:clover
