name: Publish to package
on:
  push:
    branches: [master]
  release:
      types: [created, publish]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

    - name: install deps
      run: yarn install --frozen-lockfile

    - run: yarn add sass -D

    - name: publish to NPM
      run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
